# for local dev
FROM node:18-alpine as base
RUN apk add --no-cache g++ make py3-pip libc6-compat
WORKDIR /app
COPY package*.json ./
RUN npm i
EXPOSE 3000

FROM base as dev
ENV NODE_ENV=development
COPY . .
COPY --from=base /app/node_modules /app/node_modules
CMD npm run dev
