services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app/app
    depends_on:
      database:
        condition: service_healthy
    # Add healthcheck to backend before using this
    # backend:
    #   condition: service_healthy
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/application_root/app
    # expose the fastAPI endpoints for debug purposes
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  pgdata:
